name       : qt5-multimedia
version    : 5.15.4
release    : 31
source     :
    - git|https://invent.kde.org/qt/qt/qtmultimedia.git : dc0ee181d4c56ff66c989bd3292dad7cc35e234b
homepage   : https://www.qt.io
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt5 Multimedia Components
description: |
    Qt Multimedia is an essential module that provides a rich set of QML types and C++ classes to handle multimedia content. It also provides necessary APIs to access the camera and radio functionality. The included Qt Audio Engine provides types for 3D positional audio playback and content management.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libpulse)
    - pkgconfig(openal)
    - pkgconfig(Qt5Qml)
    - pkgconfig(wayland-server)
    - pkgconfig(x11)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtmultimedia.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir -j1
