name       : qt5-multimedia
version    : 5.12.3
release    : 17
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.3/submodules/qtmultimedia-everywhere-src-5.12.3.tar.xz : a30beeb37fb284d93522e29c01fb8d12726f40e9248e80b70b1f8ab60197a301
license    :
    - GFDL-1.3
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 Multimedia Components
description: |
    Qt Multimedia is an essential module that provides a rich set of QML types and C++ classes to handle multimedia content. It also provides necessary APIs to access the camera and radio functionality. The included Qt Audio Engine provides types for 3D positional audio playback and content management.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libpulse)
    - pkgconfig(openal)
    - pkgconfig(Qt5Qml)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtmultimedia.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
